### ISSUE TITLE
DMs should display the opposing member's avatar

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/sliding-sync#166]
Currently in EX, avatars are only displayed for group chats. There's a proposed fix in Sliding Sync to also display them for DMs.

- add a new field to the room response which includes the calculated avatar, much like how we have `room.name`

**Comment by manuroe** [comment]
We discussed the problem with the EX platform team this morning. We cannot correctly "patch" it client side. 
Doing so would require to make an HTTP request for every DM room to get member state events in order to retrieve the other avatar URL.

FTR, DM room header currently looks like this in ElementX:
![IMG_7020](https://github.com/matrix-org/sliding-sync/assets/8418515/62347baf-2fd3-4119-9db8-c62b84c6d459)
(we have the avatar problem in the room list)

**Comment by pmaier1** [comment]
@kegsay Can we settle on a response so that EX could already implement it and it will just work once the backend provides it?

**Comment by kegsay** [comment]
`room.avatar` e.g:
```json
"!foo:bar": {
    "name": "Patrick Maier",
    "avatar": "mxc://...."
}
```

It'll magically start existing at some point in the future and then clients can preferentially use that.
