### ISSUE TITLE
Newly logged in SS client took ~17 minutes to receive its first to-device msgs

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#17]
I logged in as a new EX instance on my main account; device XHMEGRNTOH.  SS logged:

```
13:08:19 INF created new connection conn_id=3cb80a65324b217867aa43e807585044f0fe4a1622011c69f2a5783237ebe1cb user=@matthew:matrix.org
13:08:20 INF  ag=25 duration=1032.800977 p=0 q=1 r=21 size=328333 status=200 u=@matthew:matrix.org
13:08:30 INF  duration=9458.993342 p=1 q=2 r=0 size=250 status=200 u=@matthew:matrix.org
13:08:30 INF  duration=87.845387 p=2 q=3 r=0 size=316 status=200 u=@matthew:matrix.org
13:08:31 INF  duration=46.151764 p=3 q=4 r=1 size=1664 status=200 u=@matthew:matrix.org
13:08:37 INF  duration=5751.020204 p=4 q=5 r=0 size=250 status=200 u=@matthew:matrix.org
13:08:40 INF  duration=3154.581557 p=5 q=6 r=0 size=257 status=200 u=@matthew:matrix.org
13:08:42 INF  duration=1518.293256 p=6 q=7 r=1 size=16987 status=200 u=@matthew:matrix.org
13:08:45 INF  duration=2623.683513 p=7 q=8 r=0 size=250 status=200 u=@matthew:matrix.org
13:08:45 INF  duration=13.072967 p=8 q=9 r=0 size=250 status=200 u=@matthew:matrix.org
13:08:46 INF  duration=412.202581 p=9 q=10 r=1 size=753 status=200 u=@matthew:matrix.org
13:08:47 INF  duration=1170.252175 p=10 q=11 r=1 size=8427 status=200 u=@matthew:matrix.org
13:08:47 INF  duration=155.345102 p=11 q=12 r=1 size=1090 status=200 u=@matthew:matrix.org
13:08:54 INF  duration=7047.789753 p=12 q=13 r=0 size=254 status=200 u=@matthew:matrix.org
13:08:54 INF  duration=12.365487 p=13 q=14 r=0 size=251 status=200 u=@matthew:matrix.org
...
```

My ED spotted the new device and sent to-device msg to it, presumably to establish Olm:

```
2022-12-30T13:09:13.608Z I [!kCCQTCfnABLKGGvQjo:matrix.org] Making new Olm session for QVvZtBuJbBfc4emJh5HKcm6aWfnyQO1zhY8AK0c2hgk (@matthew:matrix.org:XHMEGRNTOH)
2022-12-30T13:09:19.260Z I Started new olm sessionid KBZhzWBKjBpfOFP/OFIxMKNLR6kRREDVEUOipXW9GYo for device @matthew:matrix.org:XHMEGRNTOH
2022-12-30T13:09:19.260Z I [!kCCQTCfnABLKGGvQjo:matrix.org] Started Olm sessions for 1 devices
2022-12-30T13:09:19.260Z I Ensured Olm sessions for devices in !kCCQTCfnABLKGGvQjo:matrix.org
2022-12-30T13:09:19.260Z I Sharing keys with newly created Olm sessions in !kCCQTCfnABLKGGvQjo:matrix.org
2022-12-30T13:09:19.260Z I Sharing megolm keys for oRuY0D/Nyc/9a7sWnDUYeN4SYgrNp9S9p0dYdQC1N90 in !kCCQTCfnABLKGGvQjo:matrix.org (slice 1/1) ["@matthew:matrix.org/XHMEGRNTOH"]
2022-12-30T13:09:19.562Z I [olmlib.encryptMessageForDevice] Using Olm session KBZhzWBKjBpfOFP/OFIxMKNLR6kRREDVEUOipXW9GYo for device @matthew:matrix.org:XHMEGRNTOH
2022-12-30T13:09:19.562Z I encryptMessage: Olm Session ID KBZhzWBKjBpfOFP/OFIxMKNLR6kRREDVEUOipXW9GYo to QVvZtBuJbBfc4emJh5HKcm6aWfnyQO1zhY8AK0c2hgk: sender chain index: 0 receiver chain indices: skipped message keys:
2022-12-30T13:09:19.592Z I Enqueuing batch of to-device messages. type=m.room.encrypted txnid=m1672405759592.24911 ["@matthew:matrix.org/XHMEGRNTOH (msgid a5835de9-1262-4be8-ba5a-931d7d0c7a0f)"]
...
2022-12-30T13:09:24.294Z I Shared megolm keys for oRuY0D/Nyc/9a7sWnDUYeN4SYgrNp9S9p0dYdQC1N90 in !kCCQTCfnABLKGGvQjo:matrix.org (slice 1/1)
...
2022-12-30T13:09:25.194Z I PUT /sendToDevice/m.room.encrypted/m1672405759592.24911 {"@matthew:matrix.org":["XHMEGRNTOH"]}
```

However, this to-device message with id `a5835de9-1262-4be8-ba5a-931d7d0c7a0f` took 17 mins to be logged by the ss proxy:

```
13:26:11 INF  d=100 duration=18.998101 p=1783 q=1784 r=0 size=23642 status=200 u=@matthew:matrix.org
...
13:26:12 INF ToDeviceTable.Messages device=3cb80a65324b217867aa43e807585044f0fe4a1622011c69f2a5783237ebe1cb msgid=a5835de9-1262-4be8-ba5a-931d7d0c7a0f
...
13:26:12 INF  d=100 duration=21.424771 p=1784 q=1785 r=0 size=24992 status=200 u=@matthew:matrix.org
```

...and only came down to my EX at `2022-12-30T13:26:12.249005Z` (with `since=7115205`).  The first to-device msgs received by that client were at `2022-12-30T13:25:58.897214Z` (with `next_batch=7114165`); everything before had next_batch=0.

So; how come it took the SS proxy 17 minutes to get & relay the to-device msg?

**Comment by ara4n** [comment]
This might not be SS's fault: https://jaeger.proxy.matrix.org/trace/b20831d3e9dccfb4 on Synapse shows that it got returned down v2 /sync at `Trace Start December 30 2022, 13:26:05.927`

**Comment by kegsay** [comment]
To device events can only be obtained from upstream via a dedicated sync v2 poller. This means you need to wait for an initial v2 sync to get that data, which for you will be about 15 minutes. This contrasts with rooms and events which we can serve up early without waiting for that poller to return, because this data is the same between devices.

In other words, this is unfortunate but expected behaviour of relying on sync v2 for data.

**Comment by ara4n** [comment]
Right, the solution to this is to have subsequent initial-syncs from the proxy filter out everything but to-device messages, which should make them ~instant.

**Comment by kegsay** [comment]
I can't do this without causing race conditions which can result in data loss.

If I have two tiers of pollers (an event poller, and a just-plain-to-device poller) then I'm prone to race conditions which can lose data if the following happens:
 - Device X is on a laggy synchrotron and is behind, but is the one syncing events
 - Device Y is on a fast synchrotron and is well ahead, but isn't getting events, only to-device msgs.
 - Device X is logged out, and Device Y takes over syncing events using Device Y's (its own) since token.
 - Device Y changes their sync filter, but not at the point device X was logged out, causing the events between the two tokens to be dropped.

I **have** to use Device X's since token, but I can't, because then I'd potentially lose to-device traffic which is just as catastrophic, because the since token encodes the to-device inbox position as well.

**Comment by kegsay** [comment]
Doing this for just initial syncs looks like:
 - Device X is syncing all data.
 - Device Y appears, syncs to-device data, then syncs all data from that point on.

Problems happen when:
 - Device X logs out at the same time Device Y appears. This can cause data loss from the point Device X got to before logging out and the since token used by Device Y when it syncs all data. If there are other users/devices in the same rooms, no data will be lost. If device X (and hence Y) are the only devices in the room, then there is a period of loss, though as https://github.com/matrix-org/sliding-sync/issues/18 mentions - we should be wiping the room data in this case as well, so it's probably fine to "lose" the data (we would've deleted it anyway!).
 - The server is killed before Device Y can complete its initial sync. Then Device X logs out. Upon restart, it isn't safe for Device Y to do a to-device only sync anymore, because Device X was logged out, even though Device Y has no since token yet. It's probably safest to just always do a complete sync in this scenario, otherwise we need to co-ordinate between the user's devices to know which devices are still running.

So I think I can do this, with caveats, for the initial sync only.
