### ISSUE TITLE
Purge pollers after device inactivity

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/sliding-sync#227]
To free up resources, we should automatically purge poller processes for devices that have become inactive.

- Inactive devices have not synced for a certain period of time
- The inactivity interval should be configurable (default: 30 days?)
- If a device comes back after inactivity, polling should recover properly

**Comment by DMRobertson** [comment]
> The inactivity interval should be configurable (default: 30 days?)

My vote would be for choosing a sensible default rather than exposing a config option.

Proposed impl:

- Hourly background job which looks for pollers whose devices haven't synced for $INACTIVITY_THRESHOLD.
 - Something like: `select user_id, device_id from tokens group by (user_id, device_id) where max(last_seen_ts) < $NOW - $INACTIVITY_THRESHOLD`. It's a scan of the tokens table, but no worse than we do on startup.
 - Needs a DB conn, so probably put it in handler2.Handler.
- Ask the poller map to stop any of these devices' pollers.
   - For each such device: act as if the token has been expired (which means deleting it from the DB). In particular, emit V2ExpiredToken on pubsub.
  - Assuming that the poller startup has completed, there shouldn't be any devices we've found that are unknown to poller. (If there were, we ought to have expired/deleted them already).
  - To enforce that assumption, don't schedule hourly cleanup until the pollers have started up.
  - Log when we expire a token due to inactivity
  - Log how many inactive tokens we found and how many pollers we closed
- For simplicity's sake, don't bother to do this kind of cleanup on startup.

**Comment by pmaier1** [comment]
> My vote would be for choosing a sensible default rather than exposing a config option.

Alright, convention over configuration. We might change this later if needed. 30 days even seems a bit long but would cover e.g., longer vacation periods. Anything between 14 and 30 days works for me, I think.

**Comment by pmaier1** [comment]
Should be finished soon.
