### ISSUE TITLE
Test Sliding Sync with OIDC

### ISSUE THREAD

**Issue by pmaier1** [matrix-org/sliding-sync#228]
@DMRobertson please fill in details if necessary

- when a device refreshes its token, its poller should continue with the new token (or else be restarted)
- when a device refreshes its token, should still be served sliding sync requests

**Comment by DMRobertson** [comment]
Key things:

- when a device refreshes its token, its poller should continue with the new token (or else be restarted)
- when a device refreshes its token, should still be served sliding sync requests

E.g.

- Have two devices A and B. A uses the proxy, B doesn't.
- Create a room with yourself only.
- Sync on device A until you see the room.
- Refresh A's access token.
- Send a message from device B into the room.
- Wait to see that message on device A.

**Comment by kegsay** [comment]
> when a device refreshes its token, its poller should continue with the new token (or else be restarted)

The poller terminates and is restarted when the next request with the new token comes in. This causes a new poller to be created, which continues with the last since value.

> when a device refreshes its token, should still be served sliding sync requests

It does, but it sends a 400 because `OnExpiredToken` knifes the connections. This isn't ideal as it's causing more initial syncs than we really want.

**Comment by kegsay** [comment]
Closing this as it 100% works, there are edge cases to iron out but they don't have a user visible impact.
