### ISSUE TITLE
[SUPPORT] Installation with Matrix Ansible behind NGINX: 404 errors when accessing /sliding-sync

### ISSUE THREAD

**Issue by randomsnowflake** [matrix-org/sliding-sync#388]
I've installed Synapse using the [Matrix Ansible Playblock](https://github.com/spantaleev/matrix-docker-ansible-deploy) ([Sliding Sync doc here](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-sliding-sync-proxy.md)). Matrix runs behind my NGINX reverse proxy.

However, it does not work: When trying to access the `matrix.mydomain/sliding-sync` URL it gives a 404 error.

It does modify the `/.well-known/matrix/client` URL, though, so the server is installed. 

Adding the NGINX config from [here](https://github.com/matrix-org/sliding-sync) does not work because the ports do not seem to be in use. 

In addition, though this is related to Element X: The client hangs with *Setting up your account, this is a onetime process, thanks for waiting*, without giving any helpful information or a way to cancel it. This is bad UI and should be changed.

I've already created a ticket with Ansible ([here](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3056)), but I'm sceptical they can help. Another user has the same issue.

**Comment by kegsay** [comment]
This isn't really the place for support queries. That being said:
- Getting 404 means some HTTP server is responding. You need to find out if this is nginx or the proxy responding. An easy way to do this is to view the URL in the browser. If you see `404 page not found` as text and nothing else, this is likely a Go server responding, so is likely the proxy. If you see "404 Not Found" with an nginx footer, this means it is never reaching the proxy.
- If the proxy is responding, then you likely have the incorrect path in your URL. **Only** the paths `/_matrix/client/v3/sync` and `/_matrix/client/unstable/org.matrix.msc3575/sync` work with the POST method, there is no welcome/landing page.
- If nginx is responding, then your ansible configuration is likely wrong, as it is not diverting request to the proxy.

>  The client hangs with Setting up your account, this is a onetime process, thanks for waiting, without giving any helpful information or a way to cancel it. 

This is likely because it cannot talk to the proxy server.
