### ISSUE TITLE
Why do we need the subscriptions API?

### ISSUE THREAD

**Issue by ara4n** [matrix-org/sliding-sync#39]
ElementX just ran into some interesting problems with the API shape, by assuming that to get room previews you have to explicitly subscribe to the rooms within a sliding window.  I explained that the sliding window can return timeline too, and that subscriptions are intended for the currently viewed room (or equivalent), but it made me wonder whether the API shape is overcomplicated by splitting subscriptions from sliding windows in this way.  Given a subscription is effectively a sliding window of size 1, why not just define it as such, and halve the API complexity?

**Comment by gnunicorn** [comment]
I'd disagree on the notion that:

> shape is overcomplicated by splitting subscriptions from sliding windows

Because you do a lookup and not a filtering of a list. It makes sense to bundle that into a lookup API.

Doing a list query of `{ list: [[0,1]], "filter": { "room_id": "SPECIFIC_ID"} }` just to say "gimme that room", is making things overcomplicated to the user IMHO.

---

Now, whether we an achieve the same we currently have the room subscription for via another way, is a different question. I am not entirely sure about the exact use case here, other than that we want "more details" for a few rooms we look at. E.g. all messages in DMs or favorites but not for the others. for that a `room_ids`-filter could make sense to me. I am not sure I see the usecase where we configure completely different state_requirements on a per-room bases ...

**Comment by kegsay** [comment]
They are semantically different things and contorting the API shape to fit into a sliding window makes no sense to me. Subscriptions are for specific rooms you are viewing: which may be 0-N. You need to know the room IDs to subscribe. Sliding windows are for specific indexes, which depends on the screen size and your current scroll position. You need to know the index positions. We specifically do NOT want clients to give a list of room IDs in the sliding window as it is wasteful on bandwidth, and clients need to know these IDs which they may not know.

If we have a window of size 1 for the subscription then we need to add filters for a list of room IDs in the window. Furthermore, the order of the rooms in this list are irrelevant, so you'd probably need to add in `slow_get_all_rooms: true` to avoid getting list operations.

It's unfair to say removal of room subscriptions halves the API complexity, given it's the sliding windows which are by far the more complex part of the API, not a map of room id to subscription.

**Comment by ara4n** [comment]
okay, i hear your points, but i suspect we will see a lot people falling in to the same trap as stefan by assuming you need to subscribe to rooms in the window in order to get room previews, etc, rather than realising that you can ask for a timeline in your sliding window.

**Comment by gnunicorn** [comment]
> but i suspect we will see a lot people falling in to the same trap as stefan by assuming you need to subscribe to rooms in the window in order to get room previews

I doubt that because the problem was that we were calculating the latest message wrong on the rust side and I proposed doing that as a fix before we released what caused it - already being suspicious as I expected the behavior to not require the subscription.

**Comment by ara4n** [comment]
ah, right, so it wasn't devx confusion but bodging around an impl detail.

i'm still a bit dubious about the overlap between the two API shapes, but i sound to be in the minority...

**Comment by kegsay** [comment]
This isn't actionable, and we've discussed it. Closing.
