### ISSUE TITLE
/versions returned HTTP 502

### ISSUE THREAD

**Issue by melroy89** [matrix-org/sliding-sync#400]
As stated earlier I'm using Synapse Docker + Nginx as my homeserver configuration. But nowhere Nginx configuration mentioned something about `/versions` location.

Anyhow, now I see this warning in sliding-sync (I got sliding-sync working now and it works with Element X). However I think Synapse and the Nginx example configurations need to be improved to avoid seeing:

```sh
16:58:40 WRN Could not contact upstream homeserver. Is SYNCV3_SERVER set correctly? error="/versions returned HTTP 502" dest=https://matrix.melroy.org
```

**Comment by melroy89** [comment]
If sliding-sync means `_matrix/client/versions`. Then I do not understand the error, since that works at my side:

https://matrix.melroy.org/_matrix/client/versions

**Comment by benyafai** [comment]
Same here, downgrading to v0.99.14 makes things work again.

**Comment by melroy89** [comment]
> Same here, downgrading to v0.99.14 makes things work again.

Uh. OK? But does that version do a version check? If so what is the url then?

**Comment by kegsay** [comment]
Downgrading _shouldn't_ help at all, as that code hasn't been touched between 0.99.14 and 0.99.15.

It will help to show the architecture here:
```
                                              +------------+
                                .-----------> | Homeserver |
                               |              +------------+
+---------+           +---------------+           ^
| Clients | <-------> | Reverse Proxy |           | /sync, /versions check
+---------+           +---------------+           v
                               |              +--------------------+
                               `------------> | Sliding Sync Proxy |
                                              +--------------------+
```

The environment variable `SYNCV3_SERVER` controls how the proxy will talk to your homeserver. On startup, the proxy will do a quick check to see if this variable seems correct. It does this by issuing an HTTP `GET /_matrix/client/versions`. If this fails, it _may_ indicate a problem with your networking (i.e `SYNCV3_SERVER` is wrong). It is only a warning because there are valid networking configurations where you can hit `/sync` and other required endpoints, but `/versions` is not allowed.

> If sliding-sync means _matrix/client/versions. Then I do not understand the error, since that works at my side:
>
> https://matrix.melroy.org/_matrix/client/versions

This is not the same thing as what I'm describing. I'm describing how to connect to your homeserver _from the point of view of a container behind the reverse proxy_. What you're doing by hitting this URL is going down the "Client -> Reverse Proxy -> Homeserver" route, which as you can see, is independent to the arrow between "Sliding Sync Proxy -> Homeserver".

Hopefully this provides enough information to debug your networking configuration.

**Comment by SoftwareSchlosser** [comment]
My synapse and syncv3 are also both running in docker containers with nginx as reverse proxy.
I am getting the same warning:
`error="Get \"http://matrix-synapse:8008/_matrix/client/versions\": dial tcp 172.21.0.3:8008: connect: connection refused" dest=http://matrix-synapse:8008`
But inside the syncv3 docker I can perfectly curl that url with the expected JSON as response!
Also the Element X app says my server doesn't support sliding sync.

**Comment by FilipSolich** [comment]
@SoftwareSchlosser I had the same problem. This is probably happening because synapse server is not fully started. I fix it with adding healthcheck to synapse server.

```yaml
healthcheck:
  test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
  interval: 15s
  timeout: 5s
  retries: 3
  start_period: 5s
```

and add `depends_on` to sliding sync.

```yaml
depends_on:
  synapse:
    condition: service_healthy
```
