### ISSUE TITLE
matrix.beeper.com on iOS 

### ISSUE THREAD

**Issue by o0oo00o0o** [matrix-org/sliding-sync#407]
When attempting to log in to Element X on iOS, a message appears saying the server doesn’t support sliding sync, however it does:

{"m.homeserver":{"base_url":"https://matrix.beeper.com"},"org.matrix.msc3575.proxy":{"url":"https://sliding-sync.beeper-tools.com"}}

**Comment by kegsay** [comment]
Indeed that URL appears to be pointing to a real proxy: https://sliding-sync.beeper-tools.com/client/server.json returns `{"server":"https://matrix.beeper.com","version":"0.99.11 (a86e01a)"}`. 

However, it does NOT appear on https://matrix.beeper.com/.well-known/matrix/client which is why Element X is saying it is unsupported:
```json
{
  "m.homeserver": {
    "base_url": "https://matrix.beeper.com/"
  },
  "m.identity_server": {
    "base_url": ""
  }
}
```

I suggest you raise this with Beeper.
