### ISSUE TITLE
Scope the connections to devices and not to a hash of the access token

### ISSUE THREAD

**Issue by sandhose** [matrix-org/sliding-sync#51]
It looks like some stuff is scoped to a hash of the access token, which will become a problem when we have refreshing access tokens, either via MSC2918 or with OIDC.

https://github.com/matrix-org/sliding-sync/blob/2c91fcb34b84821a71ac8d89da1756b047f2a59e/internal/request.go#L11-L24

It should be using the device_id instead, which are stable even when the token refreshes

Maybe related to #22?

Some (internal) discussions about that:

 - https://matrix.to/#/!TSgXVVnbcyPGrFniBq:connecteu.rs/$Bu_KKspZZD1oRW7i35jKH66mnSJz0WRODi29UZFHqZg?via=element.io&via=matrix.org&via=one.ems.host
 - https://matrix.to/#/!TSgXVVnbcyPGrFniBq:connecteu.rs/$PDCYL6WkAa7C5uN0j7a5J8e2X3Qw63DYC8IaBkBZTPs?via=element.io&via=matrix.org&via=one.ems.host

**Comment by kegsay** [comment]
> [MSC3970](https://github.com/matrix-org/matrix-spec-proposals/pull/3970) changes the scope of transaction IDs to be based on device ID instead of access token. how might this impact SS or not?

native SS implementations will treat it however homeservers do it today. Native SS doesn't modify the event in any special way. That being said, the proxy implementation DOES edit the transaction ID because that's how it can de-duplicate room data as it's multi-tenant with other users. It currently does use the access_token as a device ID, and this assumption is baked into most of the proxy as it predates the ability to get the device ID from /whoami

> how does auth work with the SS proxy and if the access token changes (i.e. a new one issued from a refresh token) will it have any impact?

it would be treated as a new device for the same user, causing a new poller to be created and an initial sync to be performed. The proxy will still be able to serve up data for the user's account instantly due to having some data from the previous token, so in theory it should Just Work with the caveat that it might take fractionally longer to sync the first time you use the new token, though I have not tested this. I assume the old token will 401/403, which will then cause the old poll loop to terminate which will then tear down the old connection. ah, though the to-device table is keyed off SHA256(access_token) so there will be a race condition where if a new to-device event arrived and before it got delivered to the client the token was invalidated, then it will be permanently lost. which isn't great. We'd need to key off a static identifier e.g SHA256(user_id $DELIMITER device_id)

**Comment by DMRobertson** [comment]
Note that this is an internal-only change, transparent to downstream clients and upstream homeservers.

> We'd need to key off a static identifier e.g SHA256(user_id $DELIMITER device_id)

Alternatively we could just store `user_id $DELIMITER device_id` directly. This has the benefit of making debugging slightly easier.

For this to work, the homeserver must consistently return a user_id with the same capitalisation (legacy mxids etc grrr). We also want the user id and device ids to have bounded length. Not sure if device ids have a maximum length in the spec? If not, we can truncate the device ID to a sensibly-sized prefix.

**Comment by DMRobertson** [comment]
> We also want the user id and device ids to have bounded length. 

[On matrix IDs](https://spec.matrix.org/v1.6/appendices/#user-identifiers):

> The length of a user ID, including the @ sigil and the domain, MUST NOT exceed 255 characters.

> Not sure if device ids have a maximum length in the spec?

Not that I can see. A quick look on Matrix.org shows that almost all (`99.9995%`) of device IDs are <= 43 characters (codepoints) long. But a large chunk of those are for signing keys, which aren't ever going to be used for syncing. Excluding singing key devices, almost all (`99.9990%`) devices are <= 16 characters (codepoints) long.

**Comment by DMRobertson** [comment]
Today's data model:

```sql
CREATE TABLE syncv3_sync2_devices
(
    device_id          TEXT NOT NULL PRIMARY KEY, -- hash(access token)
    user_id            TEXT NOT NULL,
    v2_token_encrypted TEXT NOT NULL,
    since              TEXT NOT NULL
);
```

For any given access token there is at most one row in this table. There are three states:

1. Unknown access token: no row with `device_id = hash(access_token)`
2. Unidentified access token: `device_id` and `v2_token_encrypted` present; `user_id` and `since` blank
3. Identified access token: `device_id` and `v2_token_encrypted` present; `user_id` present; `since` could be blank (no successful polls) or not (>=1 successful poll)

And there are the following operations:

- [`InsertDevice`](https://github.com/matrix-org/sliding-sync/blob/6bdef5febade70aefcae2405a530d58916daa0a9/sync2/storage.go#L145)`: Fetch or create a row with the given device ID. (State: `1->2; 2 and 3 unchanged`)
- [`RemoveDevice`](https://github.com/matrix-org/sliding-sync/blob/6bdef5febade70aefcae2405a530d58916daa0a9/sync2/storage.go#L137): Delete row with the given device ID. (State: `* -> 1`)
- [UpdateUserIDForDevice](https://github.com/matrix-org/sliding-sync/blob/6bdef5febade70aefcae2405a530d58916daa0a9/sync2/storage.go#L178): writes to user_id field. (State: `2 -> 3`)
- [UpdateDeviceSince](https://github.com/matrix-org/sliding-sync/blob/6bdef5febade70aefcae2405a530d58916daa0a9/sync2/storage.go#L173): writes to since field. (State: `3 -> 3`).

**Comment by DMRobertson** [comment]
If I had a magic wand and could do this from scratch, I'd try to eliminate state 2.

```sql
CREATE TABLE devices (
    user_id TEXT NOT NULL
    hs_device_id TEXT NOT NULL
    PRIMARY KEY (user_id, hs_device_id)
    v2_token_encrypted TEXT NOT NULL UNIQUE
    since TEXT NOT NULL
);
CREATE INDEX ON devices(v2_token_encrypted);
```

In this model:

- The primary key is the pair (user_id, hs_device_id); we track at most one token per device.
- We lookup rows by using the encrypted access token directly, rather than a hash of the access token.
- We only insert a row once we have used /whoami to associate an access token to a (user, hs_device) pair; there is no "unidentified" state.
- If an access token is refreshed, we update the encrypted access token in-place.

there are two states:

1. Unknown access token: no row with the given `encrypted_token`.
2. Identified access token: user_id, hs_device_id and v2_token_encrypted present; since could be blank (no successful polls) or not (>=1 successful poll).

and the following operations:

- IdentifyDevice: Accept a plaintext access token. Encrypt it. Look for a row with that encrypted access token. If present, return the whole row. Else, call /whoami and use that to insert a new row for that access token (then return the new row). **Overwrite any existing encrypted access token for that (user, hs_device) pair: last token wins.** (State: `1, 2 -> 2`)
- UpdateDeviceSince: as before. (State: `2 -> 2`)
- RemoveDevice: as before. (State: `2 -> 1`)

```mermaid
stateDiagram-v2
    Unknown: (1) Unknown
    Identified: (2) Identified

    Unknown --> Identified: LookupDevice
    Identified --> Unknown: RemoveDevice
    Identified --> Identified: LookupDevice

    Identified --> Identified: UpdateDeviceSince
```

**Comment by DMRobertson** [comment]
Notes:

- The proxy doesn't care about the distinction between user id and hs device id. All the other tables are keyed off one text field so it really will be easier to concate `$USER$DELIMITER$DEVICE`.
- One-off migration at startup to rewrite all tables. Write it in go code, make /whoami calls as needed.
- In a refresh tokens world we do need to be aware that tokens will expire underneath us. So we basically need to solve #18 as a prerequisite.
  - We hold onto the since tokens. Try an incremental sync afterwards, if it's not gappy then all good; if it is gappy, drop everything and initial sync.
  - Problem here: the proxy assumes that if we have room state in the proxy's DB, then it is up to date. Everything is based on the assumption of a single contiguous room timeline.
  - If we commit to refreshing access tokens (and/or to fixing #18) then that assumption is broken: the proxy might have a stale snapshot of room state. (We might get away with this if there have been only a _few_ (10) events in the room and the poller doesn't get a gappy sync response---but that is not guaranteed. Could bump up that limit.)
  - We suspect that we already have problems along these lines.

**Comment by DMRobertson** [comment]
@sandhose pointed out to me that https://github.com/matrix-org/matrix-spec-proposals/pull/3970 has landed---transaction IDs are scoped to devices (meaning userID + deviceID) and not "client session". I _think_ the proxy was already effectively doing this, but will need to check and probably write a test for this.

**Comment by DMRobertson** [comment]
Problem: how do we distinguish between a device expiry and a token expiry?

If we don't, we'll end up keeping device-scoped data forever, in particular, to-device messages. This will be A Problem.

**Comment by sandhose** [comment]
I think one potential solution would be to make the proxy OIDC-native.
The general idea is that when there is an incoming access token, it can do the introspection itself to know the mxid + device_id, and exchange that token for a longer-lived token that refreshes independently from the client access token, but where the session is still linked to it. If the client session ends, the derived token will also be revoked.

The MAS side is not really ready for that though, so it depends how much of a problem this ends up being? We could also imagine a (temporary) hacky solution, where MAS calls some special endpoint on the proxy when a device gets deleted?

**Comment by sandhose** [comment]
Long story short: soft-logout is not really usable in your case (and with Matrix refreshing tokens) and for a simple reason: the client should be able to track whenever their access tokens is about to expire, and the soft-logout would happen when it tries to refresh the token, which of course the proxy doesn't know about. The old, expired access tokens won't have a `soft_logout: true` in the error response.

**Comment by kegsay** [comment]
Why is this issue still open? We do scope to devices now. Anything else should be a separate issue (e.g cleaning up stale devices)

**Comment by kegsay** [comment]
https://github.com/matrix-org/sliding-sync/issues/127 was already made, so closing this.
