### ISSUE TITLE
Integration Flake: `TestConnBlocking`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/sliding-sync#59]
E.g. https://github.com/matrix-org/sliding-sync/actions/runs/4613594073/jobs/8155741415?pr=58#step:7:30256

```
❌ TestConnBlocking (0s)
  00:27:41 TRC OnIncomingRequest finished is_first=true is_retransmit=false is_same=false new_pos=1 num_res_acks=0 pos=0 user=dummy
      conn_test.go:125: got hi2 want hi
```

**Comment by kegsay** [comment]
This happens if the hi2 request is sent before hi, which can happen if `time.Sleep(1 * time.Millisecond) // this req happens 2nd` isn't long enough for the first request to be triggered. You can increase the frequency of this bug by removing the sleep here, which then causes both goroutines to race.

**Comment by kegsay** [comment]
The intention here is to send hi -> wait a long time -> respond and concurrently send hi2 (AFTER hi) -> wait a short time -> respond. We can remove the race by only starting the 2nd request when we have got the first request (prior to sleeping).
